on:
  schedule:
    - cron:   "*/864000 * * * *"
  workflow_dispatch:

name: job

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::gh
            any::dplyr
            any::tidyr
            any::readr
            any::knitr
            any::DT
            any::data.table
            any::ggplot2
            any::tidyverse
            any::devtools
            any::openair
            any::zoo
            any::httr
            any::usethis
            any::conflicted
            any::stringr

      - name: Cache R packages
        uses: actions/cache@v3
        id: cache
        if: runner.os != 'Windows'
        with:
          path: ${{ github.workspace }}/R/Rlibs
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}



      - name: Execute Script 1
        # executes the RScript stored in the file
        # 01-monitoring-quarto-repos/script.R
        run: |
          Rscript "R/00-preprocessing_thermo_GitHub_data.R"

      - name: Debugging Step (Print Column Names)
        run: |
          R -e '
            print("Checking DataFrame...");
            file_path4 <- read.csv("data/myfile.csv", stringsAsFactors = FALSE);
            print("Column Names:"); print(colnames(file_path4));
            file_path2 <- file_path4[file_path4$folder == "GM-RioBranco" &
                                     stringr::str_detect(file_path4$filename, ".lsi"), ];
            print("Filtered Data:"); print(file_path2);

      - name: Execute Script 2
        # executes the RScript stored in the file
        # 01-monitoring-quarto-repos/script.R
        run: |
          Rscript "R/00-data_wrangling_thermo.R"

      - name: Execute Script 3
        # executes the RScript stored in the file
        # 01-monitoring-quarto-repos/script.R
        run: |
          Rscript "R/01-AQI_calculation_thermo_data.R"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
