on:
  schedule:
    - cron:   "*/15 * * * *"
  workflow_dispatch:

name: job

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::gh
            any::dplyr
            any::tidyr
            any::readr
            any::knitr
            any::DT
            any::data.table
            any::ggplot2
            any::tidyverse
            any::devtools
            any::openair
            any::dplyr
            any::zoo
            any::httr
            any::usethis
            any::conflicted

      - name: Execute Script
        run: |
          Rscript R/job.R || echo "R script failed, check logs!"
        continue-on-error: true  # This ensures that the workflow continues even if this step fails

      - name: Next Step After Script
        run: |
          echo "This step runs regardless of the previous step's result"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
